# Generated by Django 3.1.2 on 2021-03-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20210318_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_date']},
        ),
    ]
